version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app/step1

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
